### ISSUE TITLE
Import models to PyTorch

### ISSUE THREAD

**Issue by nestarz** [yindaz/surface_normal#2]
Hi !

I'm trying to import t7 models into PyTorch, here is steps I tried:
1. Convert CUDA t7 model to CPU t7 model using this [python file](https://gist.github.com/artcg/65b04c3fa43fab02d7ebb12e33075c32#file-cuda2float-py).
2. Convert Torch model to Pytorch, failing using ([convert_torch_to_pytorch](https://github.com/clcarwin/convert_torch_to_pytorch/issues)) and this code:

```
from torch.utils.serialization import load_lua
model = load_lua('converted_to_cpu.t7',unknown_classes=True)
```

But it is failing because pytorch's load_lua doesn't support nngraph. How can I resolve it ?

I only can access the weights
```
import torchfile
stuff = torchfile.load('./model/sync_opengl_nyufinetuen_cpu.t7')
print(stuff)
[-0.29698086 -0.67621917 -0.25750896 ... -0.05081049 -0.6784678
  0.01879489]
print(stuff.shape)
(26421027,)
```
Thanks,
Elias

**Comment by yindaz** [comment]
Sorry I am not familiar with PyTorch, especially about model converting from Torch. I tried my to understand, and seems that your problem is related with nngraph. It is true that nngraph is somehow tricky to play with, and a possible solution is to use a non-nngraph version of the model and see if it can be converted to PyTorch successfully. However, I don't have such a model ready to use, and you probably need to retrain the model.

**Comment by nestarz** [comment]
Thanks for your reply @yindaz !
A last question, do you know any method to run your model using Python without retrain ?

Thanks,
Elias

**Comment by yindaz** [comment]
Sorry I don't have much experience on that. But may I know why do you need to run it in PyTorch? You can always get the result using the provided testing function. Hope it helps!

**Comment by nestarz** [comment]
I hope to integrate it with other trained models (depth, layout, ...) to build a system that reconstruct a 3D scene from a single RGB image (like https://github.com/thusiyuan/holistic_scene_parsing). I need Python to achieve it and hope to make it all in Python.

Best,
Elias

**Comment by yindaz** [comment]
I see. I am sure there are many elegant way to deal with it. But in case your want a hack, calling it from the command line and read in the result from the disk might work.

**Comment by ChuangbinC** [comment]
@nestarz Hi, do you solve this problem? I also want to use this model in pytorch.
