### ISSUE TITLE
Can't find model weight provided the website

### ISSUE THREAD

**Issue by peteryanj** [yindaz/surface_normal#3]
Hi yindaz:
 Thanks your outstanding work, I am interested in this work ,but i can't find model weight data that you provided on the website(URL), please tell me how i can download weight data.

**Comment by Azure985** [comment]
+1

**Comment by yindaz** [comment]
The links are put down as required by SUNCG authors. Sorry about the inconvenience, but we cannot share the model before further update from SUNCG.
